#!/bin/bash
echo "🚀 Starting Digicyfr Multilingual Website"
echo "========================================"
echo ""
echo "🌍 Available Languages:"
echo "  🇺🇸 English: /en"
echo "  🇵🇱 Polish:  /pl" 
echo "  🇩🇪 German:  /de"
echo "  🇫🇷 French:  /fr"
echo ""
echo "📱 Features:"
echo "  ✅ Responsive design"
echo "  ✅ Professional components"
echo "  ✅ Complete translations"
echo "  ✅ Modern UI/UX"
echo ""
echo "Starting development server..."
npm run dev
